/* The only browser-persisted value in file mode is a file handle, never study records. */
(function(root){
'use strict';
let handle=null,lastText=null,queue=Promise.resolve(),pending=0;
const sandbox=new URLSearchParams(location.search).has('sandbox'),sandboxID=(new URLSearchParams(location.search).get('sandbox')||'1').replace(/[^a-z0-9-]/gi,'').slice(0,30);
function remember(value){return new Promise((resolve,reject)=>{const request=indexedDB.open('winter-arc-file'+(sandbox?'-sandbox'+(sandboxID==='1'?'':'-'+sandboxID):''),1);request.onupgradeneeded=()=>request.result.createObjectStore('handles');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,tx=db.transaction('handles',value===undefined?'readonly':'readwrite'),store=tx.objectStore('handles'),op=value===undefined?store.get('planner'):store.put(value,'planner');let result;op.onsuccess=()=>result=op.result;tx.oncomplete=()=>{db.close();resolve(result);};tx.onerror=()=>{db.close();reject(tx.error);};};});}
function decode(text){const value=JSON.parse(text);return value.format==='winter-arc-file-v1'?value:{planner:value,timer:null};}
async function read(h){const file=await h.getFile();if(file.size>4*1024*1024)throw Error('Planner file must be smaller than 4 MB.');return {text:await file.text(),handle:h};}
async function restore(){if(!root.showOpenFilePicker)return null;let h;try{h=await remember();}catch{return null;}if(!h)return null;if(await h.queryPermission({mode:'readwrite'})!=='granted')return {pending:true};const item=await read(h);return {...item,...decode(item.text)};}
async function choose(create){const options={types:[{description:'Winter Arc planner',accept:{'application/json':['.json']}}]};if(create)return root.showSaveFilePicker({...options,suggestedName:'winter-arc.json'});return (await root.showOpenFilePicker({...options,multiple:false}))[0];}
async function reconnect(){const h=await remember();if(!h)throw Error('Choose Open planner file to reconnect.');if(await h.requestPermission({mode:'readwrite'})!=='granted')throw Error('File permission was not granted.');const item=await read(h);return {...item,...decode(item.text)};}
async function attach(item){await queue.catch(()=>{});handle=item.handle;lastText=item.text;try{await remember(handle);}catch{/* File still works this session; open it manually next time. */}}
function write(planner,timer){if(!handle)return Promise.reject(Error('No planner file connected.'));const snapshot=JSON.stringify({format:'winter-arc-file-v1',planner,timer},null,2),target=handle;pending++;const task=queue.catch(()=>{}).then(async()=>{const save=async()=>{const current=await read(target);if(lastText!==null&&current.text!==lastText)throw Error('This file changed elsewhere. Reopen it before saving; export unsaved work first.');const stream=await target.createWritable();try{await stream.write(snapshot);await stream.close();lastText=snapshot;}catch(e){try{await stream.abort();}catch{}throw e;}};if(navigator.locks)await navigator.locks.request('winter-arc-file-'+target.name,save);else await save();});queue=task;return task.finally(()=>pending--);}
root.WA_DISK={supported:!!root.showSaveFilePicker,restore,choose,reconnect,read,decode,attach,write,get handle(){return handle;},get pending(){return pending;}};
})(window);
