/* Small, dependency-free motion layer. Never changes study records or XP. */
(()=>{
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
let enabled=false,lastPage='',observer,frame=0,previous=0,accumulator=0,width=0,height=0,particles=[],wind=0,targetWind=0,scrollFrame=0;
const snow=document.querySelector('#snow');
snow.replaceChildren();
const canvas=document.createElement('canvas');canvas.setAttribute('aria-hidden','true');snow.append(canvas);
const ctx=canvas.getContext('2d');
const topButton=document.createElement('button');topButton.id='back-to-top';topButton.type='button';topButton.className='icon-button';topButton.textContent='↑';topButton.title='Back to top';topButton.setAttribute('aria-label','Back to top');topButton.hidden=true;document.body.append(topButton);
topButton.onclick=()=>window.scrollTo({top:0,behavior:enabled?'smooth':'instant'});
const quick=document.createElement('button');quick.id='motion-toggle';quick.type='button';quick.className='icon-button';quick.textContent='❄';document.querySelector('.top-tools').prepend(quick);
quick.onclick=()=>{try{checkEditable();state.settings.motion=!state.settings.motion;persist();applyTheme();const checkbox=document.querySelector('[name=motion]');if(checkbox)checkbox.checked=state.settings.motion;sync();toast(state.settings.motion?'Ambient motion on.':'Ambient motion off.');}catch(e){toast(e.message);}};
function flake(randomY=true){const depth=Math.random();return {x:Math.random()*width,y:randomY?Math.random()*height:-10,r:depth<.65?.6+depth:1.5+depth*1.7,speed:13+depth*30,phase:Math.random()*Math.PI*2,sway:4+Math.random()*14,alpha:.13+depth*.28,crystal:depth>.94,angle:Math.random()*Math.PI};}
function resize(){width=window.innerWidth;height=window.innerHeight;const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);canvas.style.width=width+'px';canvas.style.height=height+'px';ctx?.setTransform(dpr,0,0,dpr,0,0);const count=Math.min(100,Math.max(35,Math.round(width*height/14000)));particles=Array.from({length:count},()=>flake());}
function draw(now){frame=0;if(!enabled||document.hidden||!ctx)return;const elapsed=previous?Math.min((now-previous)/1000,.05):0;previous=now;accumulator+=elapsed;if(accumulator>=1/30){const dt=accumulator;accumulator=0;ctx.clearRect(0,0,width,height);wind+=(targetWind-wind)*Math.min(1,dt*1.4);const light=document.documentElement.dataset.theme==='light';const quiet=document.body.classList.contains('focus-only');for(const p of particles){p.y+=p.speed*dt;p.x+=(wind+Math.sin(now*.00045+p.phase)*p.sway)*dt;if(p.y>height+12){Object.assign(p,flake(false));}if(p.x>width+12)p.x=-10;if(p.x< -12)p.x=width+10;ctx.globalAlpha=p.alpha*(quiet?.25:1);ctx.fillStyle=light?'#5596b6':'#e2f6ff';ctx.strokeStyle=ctx.fillStyle;if(p.crystal){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle+now*.00006);ctx.lineWidth=.7;ctx.beginPath();for(let j=0;j<3;j++){const a=j*Math.PI/3;ctx.moveTo(-Math.cos(a)*p.r,-Math.sin(a)*p.r);ctx.lineTo(Math.cos(a)*p.r,Math.sin(a)*p.r);}ctx.stroke();ctx.restore();}else{ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();}}}frame=requestAnimationFrame(draw);}
function start(){if(frame||!enabled||document.hidden)return;previous=0;accumulator=0;frame=requestAnimationFrame(draw);}
function stop(){cancelAnimationFrame(frame);frame=0;previous=0;ctx?.clearRect(0,0,width,height);}
function sync(){enabled=Boolean(state.settings.motion)&&!reduce.matches;document.documentElement.classList.toggle('motion-on',enabled);quick.setAttribute('aria-pressed',String(enabled));quick.setAttribute('aria-label',reduce.matches?'Motion disabled by system preference':enabled?'Turn off ambient motion':'Turn on ambient motion');quick.disabled=reduce.matches;document.querySelectorAll('.reveal-pending').forEach(e=>{if(!enabled)e.classList.remove('reveal-pending');});if(enabled)start();else{stop();document.getAnimations().forEach(a=>a.cancel());}updateScroll();}
function reveal(){observer?.disconnect();if(!enabled)return;observer=new IntersectionObserver(entries=>{let n=0;for(const entry of entries){if(!entry.isIntersecting)continue;entry.target.classList.remove('reveal-pending');entry.target.animate([{opacity:0,transform:'translateY(14px)'},{opacity:1,transform:'translateY(0)'}],{duration:520,delay:Math.min(n++*45,135),easing:'cubic-bezier(.2,.75,.25,1)',fill:'backwards'});observer.unobserve(entry.target);}},{threshold:.06,rootMargin:'0px 0px 24px 0px'});for(const el of document.querySelectorAll('#main .card,#main .banner')){const r=el.getBoundingClientRect();if(r.top>innerHeight-20){el.classList.add('reveal-pending');observer.observe(el);}}}
function refresh(){sync();const next=location.hash||'#basecamp';if(next!==lastPage&&enabled){document.querySelector('#main').animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:280,easing:'cubic-bezier(.2,.8,.2,1)'});}lastPage=next;reveal();}
function updateScroll(){scrollFrame=0;const y=window.scrollY,max=document.documentElement.scrollHeight-innerHeight;document.body.classList.toggle('has-scrolled',y>12);document.documentElement.style.setProperty('--scroll-progress',max>0?Math.min(1,y/max):0);topButton.hidden=y<450;}
window.addEventListener('scroll',()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(updateScroll);},{passive:true});
window.addEventListener('resize',()=>{resize();updateScroll();},{passive:true});
window.addEventListener('pointermove',e=>{if(e.pointerType==='mouse')targetWind=(e.clientX/Math.max(width,1)-.5)*14;},{passive:true});
document.addEventListener('pointerleave',()=>{targetWind=0;});
document.addEventListener('visibilitychange',()=>{document.body.classList.toggle('page-hidden',document.hidden);document.hidden?stop():start();});
reduce.addEventListener('change',sync);
document.addEventListener('wa:render',refresh);
document.addEventListener('wa:theme',sync);
document.addEventListener('wa:completed',e=>{if(!enabled)return;const target=[...document.querySelectorAll('[data-action="quest-toggle"]')].find(x=>x.dataset.id===e.detail.id)?.closest('.quest');if(target){target.animate([{boxShadow:'0 0 0 0 rgba(131,221,189,.4)'},{boxShadow:'0 0 0 8px rgba(131,221,189,0)'}],{duration:600,easing:'ease-out'});target.querySelector('.check')?.animate([{transform:'scale(.7)'},{transform:'scale(1.15)'},{transform:'scale(1)'}],{duration:320});}});
document.addEventListener('keydown',e=>{if(e.defaultPrevented||e.ctrlKey||e.metaKey||e.altKey||document.querySelector('dialog[open]'))return;if(e.key==='Escape'&&document.body.classList.contains('focus-only')){document.body.classList.remove('focus-only');render();return;}if(e.key==='/'&&!e.target.closest('input,textarea,select,[contenteditable]')){const input=document.querySelector('#chapter-search');if(input){e.preventDefault();input.focus();input.select();}}});
resize();refresh();
})();
