/* Profile editing, local files and a skippable guided tour. Uses app.js helpers. */
function fileSettings(){return `<section class="card mt"><h2>A real file. On your computer.</h2><p class="muted">${disk.handle?'Connected: '+esc(disk.handle.name)+'. Changes autosave to this file.':'Create a planner file or open one you already use. Study records stay on your machine.'}</p><div class="row-actions">${disk.supported?`${button('file-create','Create planner file','','primary')}${button('file-open','Open planner file')}${button('file-reconnect','Reconnect saved file')}${disk.handle?button('file-save','Save now'):''}`:'<p>Direct file autosave needs desktop Chrome or Edge. Use Export backup / Restore backup below in this browser.</p>'}</div><p class="helper mt">Only the file connection is remembered in the browser. Permission may be requested again. Wait for “Saved to file” before closing. Keep one editing window per file.</p></section>`;}
function timerSnapshot(){return timer?{...timer,elapsed:timerElapsed(),running:false,since:null}:null;}
function recoveredTimer(value){return value&&subjects().includes(value.subject)&&Number.isInteger(value.minutes)&&value.minutes>=1&&value.minutes<=1440&&Number.isFinite(value.elapsed)&&value.elapsed>=0?{...value,elapsed:Math.min(value.elapsed,value.minutes*60000),running:false,since:null}:null;}
function saveToDisk(){if(!disk.handle)return Promise.resolve();$('#save-status').textContent='Saving to file…';return disk.write(state,timerSnapshot()).then(()=>{fileFailed=false;memoryDirty=false;storageOK=true;$('#save-status').textContent=disk.pending?'Saving to file…':'Saved to file · '+disk.handle.name;}).catch(err=>{fileFailed=true;storageOK=false;$('#save-status').textContent='File not saved — export a backup';warning(err.message+' Keep this tab open and export any unsaved work.');});}
async function adoptFile(item){const incoming=C.validate(item.planner);if(await item.handle.requestPermission({mode:'readwrite'})!=='granted')throw Error('File write permission was not granted.');await disk.attach(item);state=clone(incoming);state.settings.storageMode='file';newUser=false;fileFailed=false;loadError=false;stale=false;timer=recoveredTimer(item.timer);try{localStorage.removeItem(KEY);localStorage.removeItem(TIMER_KEY);}catch{}$('#storage-warning')?.remove();closeModal();render();$('#save-status').textContent='Saved to file · '+disk.handle.name;toast('Planner file opened. Changes will autosave here.');}
async function connectFile(create){try{if(create)checkEditable();const handle=await disk.choose(create);if(create){const item=await disk.read(handle);assert(!item.text.trim(),'This file already contains data. Use Open planner file, or choose a new filename.');await disk.attach(item);await saveToDisk();assert(!fileFailed,'File could not be saved. Export a backup before closing.');try{localStorage.removeItem(KEY);localStorage.removeItem(TIMER_KEY);}catch{}render();toast('File autosave enabled. Your study records now live in '+handle.name+'.');}else{const item=await disk.read(handle),decoded=disk.decode(item.text);C.validate(decoded.planner);modal('Open this planner file?',`<p>Open <strong>${esc(handle.name)}</strong> for ${esc(decoded.planner.settings.name)}. This replaces the workspace on screen. Export unsaved work first.</p><div class="row-actions">${button('export','Export current progress')}</div>${actions('Open and use this file')}`,()=>{adoptFile({...item,...decoded}).catch(err=>toast(err.message));});}}catch(err){if(err.name!=='AbortError')toast(err.message);}}
async function reconnectFile(){try{const item=await disk.reconnect();C.validate(item.planner);modal('Reconnect planner file?',`<p>Reopen ${esc(item.handle.name)} and use the records saved there. Export unsaved changes before reconnecting.</p>${button('export','Export current progress')}${actions('Reconnect file')}`,()=>{adoptFile(item).catch(err=>toast(err.message));});}catch(err){if(err.name!=='AbortError')toast(err.message);}}
async function boot(){try{const item=await disk.restore();if(item?.pending){newUser=false;loadError=true;page='settings';showInitial();warning('Your planner is saved in a file. Click Reconnect saved file to grant access, or Open planner file.');return;}if(item){const incoming=C.validate(item.planner);await disk.attach(item);state=clone(incoming);state.settings.storageMode='file';newUser=false;loadError=false;timer=recoveredTimer(item.timer);try{localStorage.removeItem(KEY);localStorage.removeItem(TIMER_KEY);}catch{}}}catch(err){newUser=false;loadError=true;page='settings';warning('Planner file could not be read. Open a valid file or restore a backup. '+err.message);}showInitial();if(disk.handle)$('#save-status').textContent='Saved to file · '+disk.handle.name;if(newUser&&!loadError)welcome();}
function welcome(){modal('Welcome to your Winter Arc',`<p class="muted">Choose a starting point. Every subject, chapter, exam and weekly plan is editable.</p>${field('Your name','name','Explorer','text','required maxlength="60"')}${select('Starting template','template',[['blank','Blank · college, another exam, or your own plan'],['jee','JEE + CLAT / AILET · sample chapter plan']],'blank')}${select('Save progress','storage',disk.supported?[['file','Local JSON file · recommended'],['browser','Browser storage · optional']]:[['browser','Browser storage with downloaded backups']],disk.supported?'file':'browser')}<p class="helper">Template dates are examples. Set your own timetable in Settings.</p>${actions('Create my basecamp')}`,f=>{checkEditable();assert(f.get('name').trim(),'Enter your name.');assert(newUser,'Your planner already exists. Edit it in Settings.');state.settings.name=f.get('name').trim();state.settings.setupDone=true;state.settings.storageMode=f.get('storage');if(f.get('template')==='blank'){state.settings.subjects=['Study'];state.settings.exams=[];state.settings.customGuide=true;state.chapters=[];state.weeks=[];}else state.settings.customGuide=false;newUser=false;changed('Your basecamp is ready.');startTutorial();});}
function editWorkspace(){const text=examList().map(e=>`${e.name} | ${e.date} | ${e.maxScore}`).join('\n');modal('Your subjects & exams',`<p class="muted">Use college courses, exam subjects or skill tracks. One subject per line.</p>${area('Subjects','subjects',subjects().join('\n'),'required maxlength="2000"')}${area('Exams · name | date | maximum score','exams',text,'maxlength="4000" placeholder="Semester finals | 2026-12-15 | 100"')}<p class="helper">Leave exams empty if you only want syllabus and focus tracking. Names used by existing records must remain. Add a new name instead of renaming a subject with history.</p>${actions('Save workspace')}`,f=>{checkEditable();const names=X.subjects(f.get('subjects')),examItems=X.exams(f.get('exams'));assert(examItems.every(e=>C.validDate(e.date)),'Use valid calendar dates.');const used=[...state.chapters,...state.sessions,...state.quests,...state.errors].map(x=>x.subject);if(timer)used.push(timer.subject);assert(used.every(subject=>names.includes(subject)),'Keep subject names used by chapters, sessions, blocks, mistakes or your current timer.');assert(state.mocks.every(m=>examItems.some(e=>e.name===m.exam&&m.score<=e.maxScore&&m.score>=-e.maxScore/4)),'Keep exams with existing mocks and a score scale that fits their results.');const next=clone(state);next.settings.subjects=names;next.settings.exams=examItems;C.validate(next);state=next;subjectFilter='All';changed('Subjects and exam dates saved.');});}
function bulkChapters(){modal('Paste your syllabus',`${select('Subject','subject',subjects(),subjects()[0])}${area('One chapter or topic per line','topics','','required maxlength="20000" placeholder="Limits and continuity\nDifferentiation\nApplications of derivatives"')}<p class="helper">Adds topics to your existing map. Duplicate names in this subject are skipped. Up to 200 topics at once.</p>${actions('Add syllabus topics')}`,f=>{checkEditable();const subject=f.get('subject'),names=[...new Set(f.get('topics').split('\n').map(s=>s.trim()).filter(Boolean))];assert(names.length&&names.length<=200&&names.every(s=>s.length<=200),'Enter 1–200 topics, each no longer than 200 characters.');const add=names.filter(name=>!state.chapters.some(c=>c.subject===subject&&c.name===name));for(const name of add)state.chapters.push({id:uid(),subject,name,priority:'Core',prerequisite:'',notes:'',status:'not-started',checks:[],nextReview:''});changed(`${add.length} topics added to your study map.`);});}
function chooseCompanion(){modal('Choose your study companion',`<p class="muted">Choose your partner for the climb. Your earned level stays with you. New forms unlock at levels 10 and 25.</p><div class="companion-picker">${X.companions.map(p=>`<button type="button" class="companion-option ${companion().id===p.id?'selected':''}" data-action="companion-pick" data-id="${p.id}" aria-pressed="${companion().id===p.id}"><img src="assets/${p.asset}" alt="" loading="lazy" decoding="async" width="150" height="150" class="${p.asset.endsWith('.svg')?'pixel-pet':''}"><strong>${p.name}</strong><span>${p.detail}</span></button>`).join('')}</div>${button('companion-evolution','View selected evolution path')}${button('close','Done')}`,()=>{});}
function genericGuide(){return `<details open><summary>Build your study season</summary><p>Set your subjects and exam dates in Settings. Paste your syllabus into the study map, then plan a few concrete daily blocks and one manageable week at a time.</p></details><details><summary>Practice and revision</summary><p>Learn the idea, attempt fresh questions, review errors and schedule a reattempt. Mastery needs two recent checks of at least ten questions at 75% accuracy. Adapt this check to your course; it is a study milestone, not a grade prediction.</p></details><details><summary>Focus and mocks</summary><p>Use a timer or honestly log offline study. Pause interruptions. Record mocks or course tests with your exam's score scale, then describe specific repairs.</p></details><details><summary>Rewards and recovery</summary><p>XP comes from study and review. Spend crystals on optional treats. Normal meals, sleep and breaks always belong in your day.</p></details><details><summary>Your file and your privacy</summary><p>Create or open a local JSON planner in Settings using desktop Chrome or Edge. Wait for Saved to file before closing. Reconnect file permission when needed. Keep a second copy. Export and restore backups on other browsers. There is no account, cloud sync or shared study database.</p></details>`;}
function guideSource(){return state.settings.customGuide?genericGuide():D.guide;}
function showEvolution(){const p=companion(),level=C.level(C.totalXP(state));modal(p.name+' · evolution path',`<p class="muted">Earn study XP to evolve automatically. Switching companions keeps your earned level. ${p.assets?'Each form has its own pixel character artwork.':'These forms upgrade your companion’s aura; its original sprite stays the same.'}</p><div class="evolution-path">${X.evolutionLevels.map((at,i)=>{const form=X.companionForm(p.id,at);return `<div class="evolution-form ${level<at?'locked':''} ${p.tier===i?'current':''}"><img src="assets/${form.asset}" alt="${esc(form.form)}" decoding="async"><strong>${esc(form.form)}</strong><small>Level ${at} · ${level<at?'Locked':p.tier===i?'Active':'Unlocked'}</small></div>`;}).join('')}</div><p class="helper">${p.next?`${C.threshold(p.next)-C.totalXP(state)} XP until level ${p.next}.`:'You earned the final evolution.'}</p>${button('companions','Choose companion')}${button('close','Done')}`,()=>{});}
const tutorialSteps=[
{page:'settings',target:'#main .card.mt',title:'Keep your progress on your machine',text:'Choose Create planner file, save a JSON file somewhere you can find it, and changes autosave there. Next time, reconnect it if permission is needed. Keep a second backup.',hint:'Chrome / Edge: file autosave. Other browsers: Export / Restore.'},
{page:'settings',target:'.settings-grid .card:last-child',title:'Make this fit your course',text:'Edit subjects & exams adds your college subjects or another entrance exam. Give each exam its date and maximum score. Paste syllabus adds one chapter per line.',hint:'Example: Semester finals | 2026-12-15 | 100'},
{page:'syllabus',target:'.chapter-grid',title:'Build usable knowledge',text:'Open a topic for notes and revision dates. Log fresh practice checks. Two checks with at least 10 questions and 75% correct unlock mastery.',hint:'Watching a lesson is a start. Independent practice shows what stuck.'},
{page:'roadmap',target:'.roadmap',title:'Plan a week, then adjust',text:'Add a week with work for each subject. On Basecamp, build daily blocks or add your own. Check them off after doing the work.',hint:'Leave room for tests, revision and ordinary life.'},
{page:'focus',target:'.focus-card',title:'One task. One session.',text:'Pick your subject, topic and timer length—or use custom minutes. Preview the completion chime. Pause interruptions and confirm actual minutes when logging.',hint:'Keep the tab open and unmuted for the completion sound.'},
{page:'mocks',target:'.card',title:'Turn mistakes into repairs',text:'Record a real mock or college test. Compare similar papers. Write analysis and add specific mistakes to the repair queue for spaced reattempts.',hint:'Name the next action: a concept to relearn or questions to retry.'},
{page:'life',target:'#main .card.mb',title:'Build a stronger week',text:'Log calisthenics, heavy weights or cardio for a modest daily XP bonus. Set one measurable weekly goal: chapters, routine days or any milestone. Log completed units, then claim its XP and your optional reward.',hint:'Workout XP is capped at 25 per day. Weekly-goal XP is capped at 200 per week.'},
{page:'basecamp',target:'.companion',title:'Your effort earns the levels',text:'Study and review earn XP, ranks, achievements and crystals. Choose a companion. Levels 10 and 25 unlock its next forms. Jinwoo and Naruto get new character art; the original companions gain stronger auras. Spend crystals on optional extras in Rewards & ranks.',hint:'You can replay this walkthrough from Settings.'}
];
let tutorialIndex=0,tutorialReturn='basecamp';
function startTutorial(){closeModal();tutorialReturn=page;tutorialIndex=0;showTutorial();}
function showTutorial(){document.querySelectorAll('.tour-highlight').forEach(el=>el.classList.remove('tour-highlight'));const step=tutorialSteps[tutorialIndex];go(step.page);const target=document.querySelector(step.target);target?.classList.add('tour-highlight');target?.scrollIntoView({behavior:'instant',block:'center'});const dialog=$('#tutorial');dialog.innerHTML=`<span class="eyebrow">YOUR FIRST EXPEDITION · ${tutorialIndex+1} / ${tutorialSteps.length}</span><h2 id="tutorial-title">${step.title}</h2><p>${step.text}</p><p class="tour-hint">${step.hint}</p><div class="tour-dots" aria-label="Step ${tutorialIndex+1} of ${tutorialSteps.length}">${tutorialSteps.map((s,i)=>`<span class="${i===tutorialIndex?'active':''}"></span>`).join('')}</div><div class="row-actions">${button('tutorial-skip','Skip tutorial')}${tutorialIndex?button('tutorial-back','Back'):''}${button(tutorialIndex===tutorialSteps.length-1?'tutorial-finish':'tutorial-next',tutorialIndex===tutorialSteps.length-1?'Start studying':'Next','','primary')}</div>`;if(!dialog.open)dialog.showModal();}
function tourStep(direction){tutorialIndex=Math.max(0,Math.min(tutorialSteps.length-1,tutorialIndex+direction));showTutorial();}
function endTutorial(){const dialog=$('#tutorial');dialog.close();document.querySelectorAll('.tour-highlight').forEach(el=>el.classList.remove('tour-highlight'));try{checkEditable();state.settings.tutorialDone=true;persist();}catch(err){toast(err.message);}go(tutorialReturn);}
window.addEventListener('beforeunload',e=>{if(WA_DISK.pending||memoryDirty){e.preventDefault();e.returnValue='';}});

document.querySelector('#tutorial').addEventListener('cancel',e=>{e.preventDefault();endTutorial();});
